// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlShortener.Infrastructure.Persistence.DbContext;

#nullable disable

namespace UrlShortener.Infrastructure.Migrations
{
    [DbContext(typeof(UrlDbContext))]
    [Migration("20260118131044_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UrlShortener.Infrastructure.Persistence.Entities.AboutSection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("AboutSection", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "This project was created using Angular 21, ASP.NET Core 6, EF Core 6 and MSSQL 2022.URL Checker works based on base62 encoding. Every url entry has own unique id number, so base62 will return unique short url every time for every new and current long urls.\n\nHome page is done with Angular. You can navigate through urls that are present in the table.If you are authenticated, you can create own url matches, also delete them if they are yours.Admin can delete every entry in the table.\n\nLogin page is done with Razor View. Under the hood, when user logs in, cookie is used to authenticate user. About page is done with Razor View as well, and if you are admin, you can click on text to modify it and save.",
                            Title = "About"
                        });
                });

            modelBuilder.Entity("UrlShortener.Infrastructure.Persistence.Entities.UrlData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LongValue")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ShortValue")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("LongValue", "ShortValue")
                        .IsUnique()
                        .HasFilter("[ShortValue] IS NOT NULL");

                    b.ToTable("UrlsData", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varbinary(512)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@email.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = new byte[] { 211, 33, 120, 101, 169, 107, 8, 26, 184, 165, 13, 127, 150, 82, 223, 60, 165, 177, 201, 75, 13, 248, 12, 10, 88, 93, 159, 33, 114, 200, 193, 214, 234, 189, 105, 82, 142, 5, 75, 246, 209, 234, 156, 233, 186, 7, 1, 122, 196, 206, 92, 193, 147, 37, 189, 156, 233, 230, 246, 119, 157, 74, 2, 240 },
                            PasswordSalt = new byte[] { 76, 0, 211, 160, 48, 54, 164, 0, 185, 223, 228, 224, 44, 1, 236, 87, 56, 239, 158, 33, 246, 36, 114, 110, 19, 38, 198, 11, 141, 237, 145, 225, 182, 3, 31, 87, 63, 191, 7, 114, 7, 178, 161, 147, 110, 171, 219, 202, 173, 121, 128, 223, 13, 26, 32, 11, 101, 117, 197, 194, 67, 205, 255, 126 },
                            UserRoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@email.com",
                            FirstName = "William",
                            LastName = "Erlon",
                            PasswordHash = new byte[] { 129, 48, 6, 38, 41, 8, 24, 208, 92, 59, 14, 79, 230, 38, 113, 71, 190, 246, 111, 207, 213, 240, 225, 163, 105, 190, 134, 147, 102, 80, 18, 21, 13, 237, 197, 227, 9, 201, 120, 251, 110, 43, 57, 252, 182, 52, 230, 236, 43, 101, 13, 89, 69, 196, 123, 156, 255, 144, 153, 109, 187, 79, 29, 57 },
                            PasswordSalt = new byte[] { 98, 69, 116, 93, 112, 237, 59, 37, 83, 183, 58, 28, 59, 195, 12, 214, 75, 101, 164, 194, 95, 170, 108, 77, 214, 249, 36, 94, 3, 210, 90, 181, 16, 200, 170, 116, 243, 133, 247, 87, 193, 116, 172, 234, 84, 61, 45, 45, 221, 18, 44, 44, 107, 84, 59, 78, 83, 156, 82, 4, 109, 132, 144, 22 },
                            UserRoleId = 2
                        });
                });

            modelBuilder.Entity("UrlShortener.Infrastructure.Persistence.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Role = "User"
                        });
                });

            modelBuilder.Entity("UrlShortener.Infrastructure.Persistence.Entities.UrlData", b =>
                {
                    b.HasOne("UrlShortener.Infrastructure.Persistence.Entities.User", "Owner")
                        .WithMany("Urls")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("UrlShortener.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.HasOne("UrlShortener.Infrastructure.Persistence.Entities.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("UrlShortener.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Navigation("Urls");
                });
#pragma warning restore 612, 618
        }
    }
}
